"""PROTOTYPE: render three static BizBrief concept boards; illustrative values."""

from pathlib import Path
from html import escape

ROOT = Path(__file__).parent

CSS = r"""
*{box-sizing:border-box}html,body{margin:0}body{font-family:Arial,Helvetica,sans-serif;background:#e9ebee;color:#171b21}
.board{width:1740px;min-height:940px;margin:0 auto;padding:28px 32px 34px}
.board-head{display:flex;align-items:flex-end;justify-content:space-between;margin:0 0 20px;padding:0 4px}
.eyebrow{font-size:11px;font-weight:800;letter-spacing:.18em;text-transform:uppercase}
.board h1{font-size:33px;line-height:1;margin:7px 0 5px;letter-spacing:-.045em}
.board-desc{font-size:14px;color:#59616b;margin:0}
.board-note{font-size:12px;color:#67707a;text-align:right;max-width:380px}
.phones{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}
.phone-label{font-size:12px;font-weight:800;letter-spacing:.13em;text-transform:uppercase;margin:0 0 8px;padding-left:3px;color:#404957}
.phone{height:805px;border-radius:37px;padding:7px;background:#12141a;border:2px solid #333844;box-shadow:0 16px 34px #11182726;overflow:hidden}
.screen{height:100%;border-radius:29px;overflow:hidden;position:relative;background:var(--bg);color:var(--ink)}
.status{height:32px;padding:7px 16px 0;display:flex;justify-content:space-between;align-items:center;font-size:11px;font-weight:700;letter-spacing:.02em;background:var(--status);color:var(--status-ink)}
.status .bars{font-size:10px;letter-spacing:1px}.app-head{padding:17px 19px 12px;background:var(--head);color:var(--head-ink)}
.back{font-size:12px;opacity:.75;margin-bottom:10px}.brandline{display:flex;justify-content:space-between;align-items:center}
.brand{font-size:24px;font-weight:850;letter-spacing:-.06em}.brand em{font-style:normal;color:var(--accent)}
.day{font-size:10px;letter-spacing:.11em;text-transform:uppercase;opacity:.75}.subhead{font-size:11px;opacity:.7;margin-top:3px}
.nav{display:flex;gap:3px;padding:5px;background:var(--nav);border-bottom:1px solid var(--line)}
.nav span{flex:1;text-align:center;padding:9px 2px;font-size:11px;font-weight:700;color:var(--muted);border-radius:8px}
.nav .on{color:var(--accent-ink);background:var(--accent)}
.body{height:650px;overflow:hidden;padding:15px 15px 60px}
.kicker{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.15em;color:var(--muted);margin:0 0 8px}
.section-title{font-size:14px;font-weight:800;letter-spacing:-.02em;margin:15px 0 9px;display:flex;justify-content:space-between;align-items:center}
.section-title small{font-size:10px;font-weight:700;color:var(--muted)}
.card{background:var(--card);border:1px solid var(--line);border-radius:13px;padding:13px;margin:0 0 9px;box-shadow:var(--shadow)}
.card.tight{padding:11px}.row{display:flex;justify-content:space-between;align-items:center;gap:8px}
.label{font-size:11px;color:var(--muted)}.value{font-size:21px;font-weight:800;letter-spacing:-.045em}
.strong{font-size:12px;font-weight:800}.small{font-size:10px;color:var(--muted);line-height:1.45}
.divider{height:1px;background:var(--line);margin:10px 0}.mono{font-variant-numeric:tabular-nums}
.chip{font-size:9px;font-weight:800;letter-spacing:.05em;padding:5px 7px;border-radius:5px;background:var(--soft);color:var(--accent)}
.chip.alert{background:var(--alert-soft);color:var(--alert)}.chip.ok{background:var(--ok-soft);color:var(--ok)}
.button{background:var(--accent);color:var(--accent-ink);padding:8px 10px;border-radius:7px;font-size:10px;font-weight:800;white-space:nowrap}
.button.quiet{background:var(--soft);color:var(--accent)}
.metric-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.metric-grid .card{margin:0}
.notice{border-left:3px solid var(--alert);padding:8px 10px;background:var(--alert-soft);border-radius:0 8px 8px 0;margin-bottom:6px}
.notice .strong{color:var(--alert)}.lineitem{display:flex;justify-content:space-between;font-size:11px;padding:7px 0;border-bottom:1px solid var(--line)}
.lineitem:last-child{border:0}.progress{height:6px;border-radius:8px;background:var(--soft);overflow:hidden;margin:8px 0}
.progress i{display:block;width:66%;height:100%;background:var(--accent);border-radius:8px}
.avatar{width:34px;height:34px;border-radius:10px;background:var(--soft);color:var(--accent);display:grid;place-items:center;font-size:12px;font-weight:800;flex:none}
.person{display:flex;align-items:center;gap:9px}.person-main{flex:1}.ghost-chart{height:94px;position:relative;border-bottom:1px solid var(--line);background:repeating-linear-gradient(to top,transparent 0,transparent 22px,var(--line) 23px,var(--line) 24px)}
.ghost-chart svg{position:absolute;inset:0;width:100%;height:100%}.legend{display:flex;gap:11px;font-size:9px;color:var(--muted);margin-top:7px}.dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:var(--accent);margin-right:4px}
.dot.other{background:var(--other)}.tabs-mini{display:flex;gap:5px}.tabs-mini span{font-size:9px;padding:5px 7px;background:var(--soft);border-radius:5px;color:var(--muted)}.tabs-mini .selected{background:var(--accent);color:var(--accent-ink)}
.step{display:flex;gap:4px;align-items:center}.step b{display:inline-block;background:var(--soft);padding:5px 8px;border-radius:5px;font-size:10px}
.bottom-safe{height:18px;position:absolute;bottom:0;width:100%;background:var(--bg)}.bottom-safe:after{content:'';display:block;width:95px;height:4px;border-radius:8px;background:var(--muted);opacity:.5;margin:8px auto}
.concept-a{--bg:#f5f7f8;--ink:#14232d;--head:#133e4a;--head-ink:#f4f8f8;--status:#133e4a;--status-ink:#f4f8f8;--nav:#fff;--card:#fff;--line:#dce5e8;--muted:#667b82;--accent:#06b39a;--accent-ink:#052b2a;--soft:#e4f6f2;--alert:#a95132;--alert-soft:#fff0e8;--ok:#187f69;--ok-soft:#e1f5ee;--other:#9dc6bf;--shadow:0 2px 9px #10303d0a}
.concept-b{--bg:#111b26;--ink:#e9f0f4;--head:#0b141e;--head-ink:#f1f7f9;--status:#0b141e;--status-ink:#e1ecf1;--nav:#0b141e;--card:#1b2a38;--line:#314456;--muted:#9caeba;--accent:#89dbd4;--accent-ink:#0a2027;--soft:#263b47;--alert:#ffb27f;--alert-soft:#3d302e;--ok:#99d3a5;--ok-soft:#274337;--other:#607c99;--shadow:none}
.concept-c{--bg:#f6f2eb;--ink:#2e2830;--head:#f6f2eb;--head-ink:#2e2830;--status:#f6f2eb;--status-ink:#2e2830;--nav:#f6f2eb;--card:#fffdf8;--line:#ded7cc;--muted:#746d71;--accent:#682d48;--accent-ink:#fff8f3;--soft:#eee3e5;--alert:#9c513f;--alert-soft:#f6e7e0;--ok:#536a50;--ok-soft:#e6eee0;--other:#c2aeb7;--shadow:none}
.concept-b .app-head{border-bottom:1px solid var(--line)}.concept-b .nav{border-bottom:2px solid var(--line)}.concept-b .nav .on{background:none;border-bottom:2px solid var(--accent);border-radius:0;color:var(--accent)}
.concept-b .body{padding:14px 12px 60px}.concept-b .card{border-radius:5px}.concept-b .chip,.concept-b .button{border-radius:3px}
.concept-b .section-title{text-transform:uppercase;letter-spacing:.09em;font-size:11px;color:var(--accent)}
.concept-c .brand{font-family:Georgia,serif;font-weight:700;letter-spacing:-.055em}.concept-c .app-head{border-bottom:1px solid var(--line)}
.concept-c .nav{padding:0 14px}.concept-c .nav span{border-radius:0;font-weight:600}.concept-c .nav .on{background:none;border-bottom:2px solid var(--accent);color:var(--accent)}
.concept-c .section-title{font-family:Georgia,serif;font-size:17px;font-weight:500}.concept-c .card{border-radius:2px}.concept-c .button{border-radius:2px}
.concept-c .value{font-family:Georgia,serif;font-weight:500;font-size:25px}
.concept-a .hero{background:#133e4a;color:#fff;border:0}.concept-a .hero .label,.concept-a .hero .small{color:#b7d0d2}
.concept-b .hero{border:1px solid var(--accent);background:#152a36}.concept-c .hero{border-top:3px solid var(--accent)}
.concept-c .editorial-rule{height:1px;background:var(--accent);margin:13px 0;opacity:.35}
"""

def chart(color="var(--accent)", second=False):
    other = '<polyline points="0,77 35,61 72,65 108,53 144,57 180,43 216,49 252,36 300,33" fill="none" stroke="var(--other)" stroke-width="2"/>' if second else ''
    return f'<div class="ghost-chart"><svg viewBox="0 0 300 94" preserveAspectRatio="none"><polyline points="0,73 35,65 72,57 108,63 144,45 180,54 216,32 252,37 300,20" fill="none" stroke="{color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>{other}</svg></div>'

def brief(kind):
    if kind == 'a':
        return '''<div class="kicker">Tuesday · Morning account</div>
<div class="card hero"><div class="row"><div><div class="label">Reynard's closing balance</div><div class="value mono">£1,840</div></div><span class="chip ok">+£430 NET</span></div><div class="divider"></div><div class="row small"><span>Income +£640</span><span>Expenses −£210</span><span>History ↗</span></div></div>
<div class="section-title">Needs your attention <small>2 OPEN</small></div>
<div class="notice"><div class="row"><div><div class="strong">Raid at Whitechapel</div><div class="small">Decide before end of day</div></div><span class="button">View alarm</span></div></div>
<div class="notice"><div class="row"><div><div class="strong">1 unread message</div><div class="small">Archie · new offer</div></div><span class="button quiet">Open</span></div></div>
<div class="section-title">Business funds</div><div class="metric-grid"><div class="card tight"><div class="label">Pot</div><div class="value mono">£1,220</div></div><div class="card tight"><div class="label">Float</div><div class="value mono">£340</div></div></div>
<div class="card tight" style="margin-top:8px"><div class="row"><div class="small">Move funds between cash and float</div><span class="button quiet">Manage funds</span></div></div>
<div class="section-title">Overnight operations <small>VIEW ALL</small></div><div class="card tight"><div class="lineitem"><span>Time ore produced</span><b>+12</b></div><div class="lineitem"><span>Time pearls made</span><b>+5</b></div><div class="lineitem"><span>Guard wages</span><b>−£80</b></div></div>'''
    if kind == 'b':
        return '''<div class="kicker">Account / Day 24 / Morning</div><div class="card hero"><div class="row"><div><div class="label">CLOSING / REYNARD'S</div><div class="value mono">£1,840</div></div><div style="text-align:right"><div class="chip ok">+£430</div><div class="small" style="margin-top:4px">NET CHANGE</div></div></div></div>
<div class="metric-grid"><div class="card tight"><div class="label">INCOME</div><div class="strong mono">+£640</div></div><div class="card tight"><div class="label">EXPENSES</div><div class="strong mono">−£210</div></div></div>
<div class="section-title">Action queue <small>02 / OPEN</small></div><div class="card tight"><div class="row"><span class="chip alert">URGENT</span><span class="small">DUE TODAY</span></div><div class="strong" style="margin-top:9px">Whitechapel raid</div><div class="small">Intervention closes at end of day</div><div class="divider"></div><div class="row"><span class="small">01 / Alarms</span><span class="button">REVIEW →</span></div></div><div class="card tight"><div class="row"><div><div class="strong">Unread message · Archie</div><div class="small">01 / Messages</div></div><span class="button quiet">OPEN →</span></div></div>
<div class="section-title">Treasury <small>MOVE FUNDS →</small></div><div class="card tight"><div class="row"><span>Business pot</span><b>£1,220</b></div><div class="divider"></div><div class="row"><span>Bill float</span><b>£340</b></div></div>
<div class="section-title">Operations feed <small>FULL BRIEF →</small></div><div class="lineitem"><span>TIME ORE / PRODUCED</span><b>+12</b></div><div class="lineitem"><span>PEARLS / MADE</span><b>+5</b></div><div class="lineitem"><span>GUARD WAGES / PAID</span><b>−£80</b></div>'''
    return '''<div class="kicker">The morning account · Day 24</div><div class="card hero"><div class="small">REYNARD'S · CLOSING BALANCE</div><div class="row" style="margin:10px 0"><div class="value mono">£1,840</div><span class="chip ok">+£430 today</span></div><div class="editorial-rule"></div><div class="row small"><span>Received £640</span><span>Paid £210</span><span>Ledger →</span></div></div>
<div class="section-title">For your attention <small>2 matters</small></div><div class="card"><div class="row"><span class="chip alert">TODAY</span><span class="small">01 / 02</span></div><div class="strong" style="margin-top:11px">Whitechapel is under attack</div><p class="small">A decision is due before the day ends.</p><span class="button">Open Alarms →</span><div class="divider"></div><div class="row"><div><div class="strong">A message from Archie</div><div class="small">Unread</div></div><span class="small">Read →</span></div></div>
<div class="section-title">The business purse</div><div class="card"><div class="row"><div><div class="small">OPERATING POT</div><div class="value mono">£1,220</div></div><div><div class="small">BILL FLOAT</div><div class="value mono">£340</div></div></div><div class="divider"></div><div class="row small"><span>Float pays bills when the pot cannot.</span><span>Transfer →</span></div></div>
<div class="section-title">Overnight, in brief <small>Full account →</small></div><div class="card tight"><div class="lineitem"><span>Time ore brought in</span><b>12</b></div><div class="lineitem"><span>Time pearls made</span><b>5</b></div><div class="lineitem"><span>Guard wages paid</span><b>£80</b></div></div>'''

def manage(kind):
    if kind == 'a':
        return '''<div class="kicker">Sales · production · procurement</div><div class="section-title">Sales pipeline <small>1 OFFER · 2 ACTIVE</small></div><div class="card"><div class="row"><span class="chip">WEEKLY OFFER</span><span class="small">Expires Day 27</span></div><div class="strong" style="margin:10px 0 4px">6 Time ore · The Guild</div><div class="row"><span class="value mono">£360</span><div><span class="button quiet">Decline</span> <span class="button">Accept</span></div></div></div><div class="card tight"><div class="row"><div><div class="strong">01 · Stepney order</div><div class="small">4 / 6 Time ore · due Day 26</div></div><span class="chip ok">ACTIVE</span></div><div class="progress"><i></i></div><div class="row small"><span>Buy missing calc: off</span><span>Priority ↕</span></div></div>
<div class="section-title">Production <small>LOG →</small></div><div class="card tight"><div class="row"><div><div class="strong">Time pearl</div><div class="small">Personal target 5 · contract need 3</div></div><span class="step"><b>−</b><b>5</b><b>+</b></span></div><div class="divider"></div><div class="row"><span class="small">Cover contract needs</span><span class="chip ok">ON</span></div></div>
<div class="section-title">Procurement <small>ASSIGN VEINS →</small></div><div class="card tight"><div class="row"><div><div class="strong">Owen · Cultivation</div><div class="small">Whitechapel — Time</div></div><span class="step"><b>−5</b><b>10</b><b>+5</b></span></div></div>'''
    if kind == 'b':
        return '''<div class="kicker">Operations / Sales</div><div class="card hero"><div class="row"><div><div class="label">ORDER FLOW</div><div class="value">2 active</div></div><span class="chip">1 NEW</span></div><div class="divider"></div><div class="small">Sales delivers from shared stock at block end.</div></div><div class="section-title">01 / Incoming offer</div><div class="card"><div class="row"><span class="chip">WEEKLY</span><span class="small">EXP DAY 27</span></div><div class="strong" style="margin:9px 0 2px">THE GUILD / TIME ORE ×6</div><div class="row"><span class="value mono">£360</span><span class="button">ACCEPT →</span></div><div class="small">Decline offer ↗</div></div><div class="section-title">02 / Delivery order <small>DRAG TO PRIORITISE</small></div><div class="card tight"><div class="row"><span class="strong">≡ 01 · Stepney order</span><span class="chip ok">ACTIVE</span></div><div class="small">4 / 6 Time ore · due Day 26</div><div class="progress"><i></i></div><div class="row small"><span>BUY MISSING CALC · OFF</span><span>DETAILS →</span></div></div><div class="section-title">03 / Production</div><div class="card tight"><div class="row"><span class="strong">Time pearl</span><span class="step"><b>−</b><b>5</b><b>+</b></span></div><div class="small">Personal 5 + contract need 3 · cover on</div></div><div class="section-title">04 / Procurement</div><div class="card tight"><div class="row"><span>Owen / Whitechapel — Time</span><span class="strong">10 ▸</span></div><div class="small">Vein Station target · adjust in detail</div></div>'''
    return '''<div class="kicker">Work in progress</div><div class="section-title">Orders and offers <small>See history →</small></div><div class="card hero"><div class="row"><div class="small">NEW · WEEKLY</div><span class="small">Ends Day 27</span></div><div class="strong" style="font-size:16px;margin:12px 0 4px">The Guild wants six Time ore</div><div class="small">Recurring order · payment each delivery</div><div class="editorial-rule"></div><div class="row"><span class="value mono">£360</span><div><span class="small">Decline</span> &nbsp; <span class="button">Accept order</span></div></div></div><div class="card tight"><div class="row"><div><div class="strong">Stepney order</div><div class="small">4 of 6 Time ore · due Day 26</div></div><span class="small">Details →</span></div><div class="progress"><i></i></div><div class="small">First in delivery priority · drag to reorder</div></div>
<div class="section-title">Make <small>Production log →</small></div><div class="card tight"><div class="row"><div><div class="strong">Time pearls</div><div class="small">Personal target 5 · 3 needed by contract</div></div><span class="step"><b>−</b><b>5</b><b>+</b></span></div><div class="divider"></div><div class="small">✓ Cover contract needs</div></div>
<div class="section-title">Gather <small>Vein assignments →</small></div><div class="card tight"><div class="row"><div><div class="strong">Owen · Whitechapel</div><div class="small">Time ore · Vein Station</div></div><span class="strong">10 →</span></div></div>'''

def staff(kind):
    if kind == 'a':
        return '''<div class="kicker">People and pay</div><div class="metric-grid"><div class="card tight"><div class="label">Working</div><div class="value">2</div></div><div class="card tight"><div class="label">Wages owed</div><div class="value mono">£40</div></div></div><div class="section-title">Team <small>ROLES TAKE EFFECT NEXT BLOCK</small></div><div class="card"><div class="person"><span class="avatar">OW</span><div class="person-main"><div class="strong">Owen</div><div class="small">Cultivation · unpaid</div></div><span class="chip alert">£40 OWED</span></div><div class="divider"></div><div class="row small"><span>Share of payday remainder</span><b>15%</b></div><div class="lineitem"><span>Cultivating skill</span><b>4 · 18 XP</b></div><div class="lineitem"><span>Production skill</span><b>2 · 6 XP</b></div><div class="row" style="margin-top:12px"><span class="button quiet">Change role</span><span class="button">Top up £40 & pay</span></div></div><div class="card"><div class="person"><span class="avatar">JA</span><div class="person-main"><div class="strong">James</div><div class="small">Production · working</div></div><span class="chip ok">PAID</span></div><div class="divider"></div><div class="row small"><span>Share of payday remainder</span><b>20%</b></div><div class="lineitem"><span>Crafting skill</span><b>5 · 22 XP</b></div><div class="row" style="margin-top:10px"><span class="button quiet">Change role</span><span class="small">Role options →</span></div></div><div class="small">Vein assignments are under Manage → Procurement.</div>'''
    if kind == 'b':
        return '''<div class="kicker">Roster / 02 Recruited</div><div class="card hero"><div class="row"><div><div class="label">PAYROLL EXPOSURE</div><div class="value mono">£40 owed</div></div><span class="chip alert">ACTION</span></div></div><div class="section-title">01 / Owen</div><div class="card"><div class="row"><div class="person"><span class="avatar">OW</span><div><div class="strong">CULTIVATION</div><div class="small">Unpaid · 15% remainder</div></div></div><span class="chip alert">DUE</span></div><div class="divider"></div><div class="lineitem"><span>CULTIVATING</span><b>LV 4 / 18 XP</b></div><div class="lineitem"><span>PRODUCTION</span><b>LV 2 / 6 XP</b></div><div class="row" style="margin-top:11px"><span class="button quiet">ROLE ▾</span><span class="button">PAY £40 →</span></div></div><div class="section-title">02 / James</div><div class="card"><div class="row"><div class="person"><span class="avatar">JA</span><div><div class="strong">PRODUCTION</div><div class="small">Working · 20% remainder</div></div></div><span class="chip ok">CLEAR</span></div><div class="divider"></div><div class="lineitem"><span>CRAFTING</span><b>LV 5 / 22 XP</b></div><div class="row" style="margin-top:11px"><span class="button quiet">ROLE ▾</span><span class="small">DETAILS →</span></div></div><div class="section-title">Assignments</div><div class="card tight"><div class="row"><span>Vein picking</span><span class="small">MANAGE / PROCUREMENT →</span></div></div>'''
    return '''<div class="kicker">The people</div><div class="section-title">A small team, clear account</div><div class="card hero"><div class="row"><div><div class="small">WAGES CURRENTLY OWED</div><div class="value mono">£40</div></div><span class="chip alert">Owen</span></div><div class="small" style="margin-top:7px">Pay from your cash to clear the balance.</div></div><div class="card"><div class="person"><span class="avatar">OW</span><div class="person-main"><div class="strong">Owen</div><div class="small">Cultivation · 15% of payday remainder</div></div><span class="small">Edit →</span></div><div class="editorial-rule"></div><div class="row"><div><div class="small">STATUS</div><div class="strong">Unpaid · £40</div></div><span class="button">Top up and pay</span></div><div class="divider"></div><div class="small">Cultivating 4 · 18 XP &nbsp; / &nbsp; Production 2 · 6 XP</div></div><div class="card"><div class="person"><span class="avatar">JA</span><div class="person-main"><div class="strong">James</div><div class="small">Production · 20% of payday remainder</div></div><span class="small">Edit →</span></div><div class="editorial-rule"></div><div class="row"><span class="small">Working · wages current</span><span class="chip ok">CLEAR</span></div><div class="divider"></div><div class="small">Crafting 5 · 22 XP</div></div><div class="section-title">Where they work</div><div class="card tight"><div class="row"><span class="small">Vein assignments live in Procurement</span><span class="strong">Open →</span></div></div>'''

def stats(kind):
    if kind == 'a':
        return '''<div class="kicker">Last 10 days · Business performance</div><div class="metric-grid"><div class="card tight"><div class="label">Revenue</div><div class="value mono">£3,460</div><div class="small">10-day total</div></div><div class="card tight"><div class="label">Expenses</div><div class="value mono">£1,180</div><div class="small">10-day total</div></div></div><div class="section-title">Cash flow <small>DAILY</small></div><div class="card"><div class="row"><span class="strong">Revenue and expenses</span><span class="chip">10 DAYS</span></div>'''+chart(second=True)+'''<div class="legend"><span><i class="dot"></i>Revenue</span><span><i class="dot other"></i>Expenses</span></div></div><div class="section-title">Expense mix <small>GUARD COSTS →</small></div><div class="card tight"><div class="lineitem"><span>Staff wages</span><b>£590</b></div><div class="lineitem"><span>Guard wages ↗</span><b>£420</b></div><div class="lineitem"><span>Calc bought</span><b>£170</b></div></div><div class="section-title">Output</div><div class="card tight"><div class="row"><span class="strong">Ore collected</span><span class="tabs-mini"><span class="selected">Cultivators</span><span>You</span></span></div>'''+chart()+'''<div class="small">Items produced: 18 over 10 days</div></div>'''
    if kind == 'b':
        return '''<div class="kicker">Performance / 10-day window</div><div class="card hero"><div class="row"><div><div class="label">REVENUE</div><div class="value mono">£3,460</div></div><div style="text-align:right"><div class="label">EXPENSES</div><div class="strong mono">£1,180</div></div></div></div><div class="section-title">Daily trend</div><div class="card tight">'''+chart(second=True)+'''<div class="legend"><span><i class="dot"></i>REVENUE</span><span><i class="dot other"></i>EXPENSES</span></div></div><div class="section-title">Expense analysis <small>GUARD DETAIL →</small></div><div class="card tight"><div class="lineitem"><span>STAFF WAGES</span><b>£590</b></div><div class="lineitem"><span>GUARD WAGES ↗</span><b>£420</b></div><div class="lineitem"><span>CALC BOUGHT</span><b>£170</b></div></div><div class="section-title">Ore yield <small>COLLECTION SOURCE</small></div><div class="tabs-mini" style="margin-bottom:9px"><span class="selected">CULTIVATORS</span><span>YOU</span></div><div class="card tight">'''+chart()+'''</div><div class="section-title">Items produced</div><div class="card tight"><div class="row"><span>10-DAY TOTAL</span><b>18</b></div></div>'''
    return '''<div class="kicker">The figures · last ten days</div><div class="card hero"><div class="small">BUSINESS PERFORMANCE</div><div class="row" style="margin-top:10px"><div><div class="small">Revenue</div><div class="value mono">£3,460</div></div><div><div class="small">Expenses</div><div class="value mono">£1,180</div></div></div></div><div class="section-title">Money over time</div><div class="card">'''+chart(second=True)+'''<div class="legend"><span><i class="dot"></i>Revenue</span><span><i class="dot other"></i>Expenses</span></div></div><div class="section-title">Where it went</div><div class="card tight"><div class="lineitem"><span>Staff wages</span><b>£590</b></div><div class="lineitem"><span>Guard wages</span><b>£420 →</b></div><div class="lineitem"><span>Calc bought</span><b>£170</b></div></div><div class="section-title">What came in</div><div class="card tight"><div class="row"><div class="strong">Ore collected</div><div class="tabs-mini"><span class="selected">Cultivators</span><span>You</span></div></div>'''+chart()+'''<div class="divider"></div><div class="row"><span class="small">Items made</span><b>18</b></div></div>'''

SCREENS = [('Brief',brief),('Manage',manage),('Staff',staff),('Stats',stats)]
CONCEPTS = {
    'a': ('01 / CLEARLINE', 'Focused business dashboard', 'Bright, decisive fintech. Urgent work first; money and operations one glance below.'),
    'b': ('02 / CONTROL ROOM', 'Dense operations console', 'For players who manage many contracts: queue, priority, payroll, and trends in a compact command view.'),
    'c': ('03 / PRIVATE OFFICE', 'Editorial business ledger', 'Quiet, premium and human. A disciplined account book with modern task cues.'),
}

def phone(kind, active, content):
    nav = ''.join(f'<span class="{"on" if name == active else ""}">{name}</span>' for name,_ in SCREENS)
    return f'''<div><div class="phone-label">{active}</div><div class="phone"><div class="screen concept-{kind}"><div class="status"><span>08:14</span><span class="bars">▂▄▆  ◉  ▰ 87%</span></div><div class="app-head"><div class="back">‹ Phone</div><div class="brandline"><div class="brand">Biz<em>Brief</em></div><div class="day">Day 24 · Morning</div></div><div class="subhead">Business, under control.</div></div><div class="nav">{nav}</div><div class="body">{content}</div><div class="bottom-safe"></div></div></div></div>'''

for key,(name,title,desc) in CONCEPTS.items():
    phones = ''.join(phone(key,tab,fn(key)) for tab,fn in SCREENS)
    html = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=1740"><title>BizBrief — {escape(name)}</title><style>{CSS}</style></head><body><main class="board"><header class="board-head"><div><div class="eyebrow">BizBrief · static concept</div><h1>{escape(name)} — {escape(title)}</h1><p class="board-desc">{escape(desc)}</p></div><div class="board-note">Illustrative data · established game actions only<br>Brief / Manage / Staff / Stats · phone-sized views</div></header><div class="phones">{phones}</div></main></body></html>'''
    (ROOT / f'concept-{key}.html').write_text(html, encoding='utf-8')
    print(ROOT / f'concept-{key}.html')
